mutation SignUpMutation(
  $email: String!
  $username: String!
  $password: String!
  $firstname: String!
  $lastname: String!
) {
  signUp(
    email: $email
    username: $username
    password: $password
    firstname: $firstname
    lastname: $lastname
  ) {
    id
    email
  }
}
